### ISSUE TITLE
Audio transmitter noise

### ISSUE THREAD

**Issue by yashmewada9618** [Mark-MDO47/BluetoothAudioTransmitter_KCX_BT_EMITTER#1]
Hello,
I have a small project in which I need to transmit the audio from my microphone output to a specific headphone. Although the connection part was easy and required no major inputs. I am using a CCTV microphone preamp circuit board and it does output an amplified voice but the thing is along with this amplified voice I do get a significant loud noise. This noise isn't any hummm or any other noise it sounds like when something isn't connected well. I thought the issue was with the mic circuit and tried 6-7 different circuits but the amplitude of noise remained the same throughout the different circuits. When I try to give it input from the aux cable it transmits audio without any noise and perfect;y.
It's been 1 month since this and I am unable to find the source of the problem and as you know the is literally nothing on the net regarding this and I found no significant platform to write my issue so I wrote it here with the hope you might help me.
Sorry if I am wrong.
Can you help me with this? Do I need to route any external components to convert the mic preamp output to line level input?
Right now I am powering this module with a 3.7v 300mAh lipo battery.
Below is the circuit diagram I am using right now along with the microphone preamp module.
The only issue here is when I connect any microphone preamp circuit there is significant oud noise and I tried many filter circuits too but the noise remains the same.
Please help/guide me with this issue.
![kcx](https://user-images.githubusercontent.com/54842967/117851251-c174c200-b2a3-11eb-969b-d20309e13d6d.png)
https://micronic.co.uk/products/waterproof-outdoor-cctv-microphone-pre-amp-module-with-rca-female-phono-audio-output-2-1mm-dc-socket

**Comment by Mark-MDO47** [comment]
Sorry if this is too late to help. My experience was that the INR/INL inputs were "line" inputs, not normal "speaker" inputs. In my circuit I was using a YX5200 which had both SPK1/SPK2 outputs and also DacR/DacL outputs. I got MUCH better results connecting the KCX_BT_EMITTER with the DacR/DacL outputs from the YX5200. I also found that it was important to have an analog ground between the input source and the KCX_BT_EMITTER.
Sorry to say, I am not an expert in this area but am just a hobbyist, so I don't actually know the technical difference between "line" I/O and "speaker" I/O. Also I found a way to get a working analog ground by just trial and error. Still, I hope this helps.
Mark

**Comment by DrJapan** [comment]
Hello!

When you say, "Also I found a way to get a working analog ground by just trial and error." Where did you find this ground? Could you elaborate?

**Comment by Mark-MDO47** [comment]
Obviously the AGND pin on the KCX_BT_EMITTER is analog ground. If I connected all the grounds together in our Rubber Band Gun project I got a loud hum. I found by experiment when using the YX5200 module as the source of the sound that one of its pins was usable to connect to the KCX_BT_EMITTER AGND.

If you look at the schematic here on the first page
https://github.com/Mark-MDO47/RubberBandGun/blob/master/RubberBandGun_Wiring.pdf

You can see that the YX5200 module pin 7 (GND) is connected to the KCX_BT_EMITTER pin AGND. By keeping these two ground pins isolated from all the other grounds, the hum went away. Note that the YX5200 pin 10 (GND) is connected to the standard ground as are all the digital chips.

**Comment by Mark-MDO47** [comment]
Sorry - I thought  I replied to this but I guess I didn't finish it.

If you look for instance at the first page of the schematic for the SciFi Rubber Band Gun here
https://github.com/Mark-MDO47/RubberBandGun/blob/master/RubberBandGun_Wiring.pdf

You can see that the YX5200 (audio source) has a GND pin on both 7 and 10. The KCX_BT_EMITTER has a PGND and an AGND pin. I think the AGND is "audio" ground or "analog" ground. I didn't find any documentation of what the two ground pins on the YX5200 are.

If I connected the standard ground to the AGND pin I heard a lot of noise on the speakers. After some experimentation I connected YX5200 GND pin 7 to KCX_BT_EMITTER AGND and GND pin 10 to PGND. This was the best combination I could discover, and I don't hear that noise on the speakers now.
