### ISSUE TITLE
Question - programming

### ISSUE THREAD

**Issue by Unomobil** [Mark-MDO47/BluetoothAudioTransmitter_KCX_BT_EMITTER#10]
Hi 
Im am new at this 😅. 
is it possible to do any programming of the module ?. 
i would need to have the mic recieved from bluetooth  headset, and also the sound output from the board OFF, until a button is activate :). 

Case: walkietalkie mic and headset, by bluetooth

The radio have: two phone jacks. One for output, one for mic.
BUT, it is ONE WAY, communication. So i am not able to answer, when another is talking. 
so if the output for mic is activated, all communication will be blocked 🙈. So i need to have at button to push when walking. 

(Also i will have limited space for the bluetoot device/board). 

Is it possible ? Or do i need to sesrch for something else ? 

best
Michael
DK

**Comment by Mark-MDO47** [comment]
Not sure I understand the scenario you are describing, but the KCX_BT_EMITTER is a transmit-only device. If you were going to use Bluetooth in both directions you might want to look for a module that does that. If I misunderstood please let me know.

**Comment by Unomobil** [comment]
Sorry my mistake :).
