### ISSUE TITLE
ESP32 Support

### ISSUE THREAD

**Issue by fahmij8** [Mark-MDO47/BluetoothAudioTransmitter_KCX_BT_EMITTER#2]
First of all, thank you for the great documentation and youtube video explanation. But I have further question, is [this](https://github.com/Mark-MDO47/BluetoothAudioTransmitter_KCX_BT_EMITTER/blob/master/ProgrammingArduino/ProgrammingArduino.ino) particular code can be used for the ESP32 Board? I also try to use [this](https://github.com/Mark-MDO47/BluetoothAudioTransmitter_KCX_BT_EMITTER/blob/322052b0264e2e3d7cf68493d9b03a5eabf71031/ProgrammingArduino/ProgrammingArduino.ino) one, but it doesn't seem to show anything on the serial monitor as output.

**Comment by Mark-MDO47** [comment]
The code itself should work on an ESP32, but the ESP32 boards I know of have 3.5 V outputs and the Bluetooth module expects 5 V inputs. As the referenced document in that repository says (https://github.com/Mark-MDO47/BluetoothAudioTransmitter_KCX_BT_EMITTER/blob/master/ProgrammingArduino_SerialMonitor_SampleOutput.pdf) "The Programming Arduino should be a type of Arduino that uses 5 Volt interfaces. For example, an Arduino Uno or an Arduino Nano Classic."
The easiest approach I can think of would be to get a cheap Arduino Uno or Arduino Nano clone for this usage. Alternatively, you could look for a 3.5 V to 5 V buffer driver.

**Comment by fahmij8** [comment]
Thank you so much for the explanation, closing the issue at once
