### ISSUE TITLE
Emitting mode

### ISSUE THREAD

**Issue by zyssai** [Mark-MDO47/BluetoothAudioTransmitter_KCX_BT_EMITTER#3]
Hi, and thanks for your work with this project.

It's not really an issue, but I am really stuck with this BT transmitter and don't really know what can I do.
Sorry for this long explaination, hope it will be clear enough.

I have an amplifier that have analog and BT input.
I always use it in analog mode, and my smartphone is always connected to BT, so when I start a song, the amplifier switches from analog to BT entry automatically, and then if I stop the song, amplifier comes back to analog.

Now here is the problem.
For my project I am building a player, with inside it a KCX_BT_EMITTER.
So I correctly connected my player to the INR and INL entry of the KCX (I know that they are low level, no problem), and connected it to the BT amplifier receiver.
It is working perfectly, but I have one major problem, KCX is ALWAYS in emitting mode, even if no sound is coming from the input.

I'm really stuck with it, with the BT of my smartphone, my amplifier can switch correctly when there is no sound, but with the KCX it is always in BT receiver mode.

By chance, do you have an idea of what can I do?

Best regards.
Jc

**Comment by Mark-MDO47** [comment]
I can think of two ways to get the KCX_BT_EMITTER to stop emitting, either

1. power the KCX_BT_EMITTER module off or
2. reprogram the KCX_BT_EMITTER to connect only to a bluetooth address that is fake and doesn't exist

For the second method, see https://github.com/Mark-MDO47/BluetoothAudioTransmitter_KCX_BT_EMITTER/blob/master/ProgrammingArduino_SerialMonitor_SampleOutput.pdf

First clear all the device information from the VMLINK storage in the KCX_BT_EMITTER, then add a "fake" address to the storage, then reset the KCX_BT_EMITTER.

If you were using my ProgrammingArduino.ino code (https://github.com/Mark-MDO47/BluetoothAudioTransmitter_KCX_BT_EMITTER/blob/master/ProgrammingArduino/ProgrammingArduino.ino), you would issue commands in this order:
4 - Delete all auto-connect Bluetooth receiver devices from storage
3 - Add one auto-connect Bluetooth receiver device to storage
* (here is where you add a "fake" address, it will automatically reset after)

You could try just doing a disconnect command (AT+DISCON) but I suspect it would reconnect.

Good luck!
Mark

**Comment by Mark-MDO47** [comment]
I re-opened it in case there were further comments.

**Comment by zyssai** [comment]
Hi, really appreciate the time you took to give me this detailed answer.

I have thought about those solutions, power off the module, or disconnect it.
But for my project I will need to pass audio output of phone calls, and this is the major problem, I cannot have a huge delay between start of play and the switch to BT entry of the amplifier.

@dhcnet47 from another project just point me to an interesting idea, that could possibly be a noise problem, there should too much noise coming from output of KCX module to permanently switch my amplifier.
I will investigate this way and make some tests.

Once again, thanks!

Edit: I have made some further tests, and even if I put INR and INL to audio ground, KCX stays in emitting mode. Very strange.
I think I will buy another model of BT transmitter.

**Comment by Mark-MDO47** [comment]
Good luck! I am closing this one
