### ISSUE TITLE
Errors When Uploading

### ISSUE THREAD

**Issue by DrJapan** [Mark-MDO47/BluetoothAudioTransmitter_KCX_BT_EMITTER#6]
Hello!

I'm getting the following errors, when trying to upload the sketch, to my Arduino Uno.

/Users/ttmedia/Documents/Arduino/KCX_BT_Emitter/KCX_BT_Emitter.ino: In function 'uint8_t buildADDLINKADD(char*, uint16_t)':
/Users/ttmedia/Documents/Arduino/KCX_BT_Emitter/KCX_BT_Emitter.ino:288:50: warning: unused parameter 'cmdMaxLen' [-Wunused-parameter]
 uint8_t buildADDLINKADD(char * cmdAddr, uint16_t cmdMaxLen) {
                                                  ^~~~~~~~~
/Users/ttmedia/Documents/Arduino/KCX_BT_Emitter/KCX_BT_Emitter.ino: In function 'uint8_t buildADDLINKNAME(char*, uint16_t)':
/Users/ttmedia/Documents/Arduino/KCX_BT_Emitter/KCX_BT_Emitter.ino:349:16: warning: unused variable 'zeroFill' [-Wunused-variable]
   char const * zeroFill = "000000000000";
                ^~~~~~~~
/Users/ttmedia/Documents/Arduino/KCX_BT_Emitter/KCX_BT_Emitter.ino:347:51: warning: unused parameter 'cmdMaxLen' [-Wunused-parameter]
 uint8_t buildADDLINKNAME(char * cmdAddr, uint16_t cmdMaxLen) {
                                                   ^~~~~~~~~
/Users/ttmedia/Documents/Arduino/KCX_BT_Emitter/KCX_BT_Emitter.ino: In function 'uint8_t getSerial_chars()':
/Users/ttmedia/Documents/Arduino/KCX_BT_Emitter/KCX_BT_Emitter.ino:399:19: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
       if ((idx+2) <= NUMOF(inBytes)) {
/Users/ttmedia/Documents/Arduino/KCX_BT_Emitter/KCX_BT_Emitter.ino: In function 'void testEcho()':
/Users/ttmedia/Documents/Arduino/KCX_BT_Emitter/KCX_BT_Emitter.ino:470:7: warning: unused variable 'loopIdx' [-Wunused-variable]
   int loopIdx;

**Comment by DrJapan** [comment]
Also, I was trying to add a HELP command to the project, but for some reason, I can't see an output.

#define DPIN_BLUESRL_RX   9  // serial in  - talk to Bluetooth module (KCX_BT_EMITTER) - connect to YELLOW wire
#define DPIN_BLUESRL_TX   2  // serial out  - talk to Bluetooth module (KCX_BT_EMITTER) - connect to GREEN wire

SoftwareSerial myBlueSerial(DPIN_BLUESRL_RX, DPIN_BLUESRL_TX); // to talk to Bluetooth 


#define NUMWAIT  3000 // loopcount waiting for response from Bluetooth module

#define NUMOF(a) (sizeof((a)) / sizeof(*(a)))

uint8_t DEBUG_SERIAL_IN = 0; // 1 to debug the serial input code

char inBytes[100];
char const * cmd_AT          = "AT+";
char const * cmd_HELP        = "AT+HELP";
char const * cmd_REST        = "AT+REST";
char const * cmd_GMR         = "AT+GMR";
char const * cmd_STATUS      = "AT+STATUS";
char const * cmd_DISCON      = "AT+DISCON";
char const * cmd_SCAN        = "AT+SCAN";
char const * cmd_ADDLINKADD  = "AT+ADDLINKADD=0x"; // NOTE: must be exactly 12 characters for hex string
char const * cmd_ADDLINKNAME = "AT+ADDLINKNAME=";
char const * cmd_VMLINK      = "AT+VMLINK?";
char const * cmd_DELVMLINK   = "AT+DELVMLINK";

char cmd_bld_ADDLINKADD[32];  // must build these in RAM from user input
char cmd_bld_ADDLINKNAME[64]; // must build these in RAM from user input

char const * cmdsScan[]     = {cmd_AT, cmd_REST, cmd_SCAN};
char const * cmdsDispRAM[]  = {cmd_AT, cmd_REST, cmd_VMLINK};
char const * cmdsAddRAM[]   = {cmd_AT, cmd_DISCON, cmd_VMLINK, cmd_bld_ADDLINKADD, cmd_bld_ADDLINKNAME, cmd_REST, cmd_VMLINK};
char const * cmdsClearRAM[] = {cmd_AT, cmd_REST, cmd_DISCON, cmd_DELVMLINK, cmd_REST, cmd_VMLINK};
char const * cmdsHelp[]     = {cmd_AT, cmd_GMR, cmd_HELP};


char const * menuOptions[5] = { "\n1=SCAN", "\n2=DISPLAY", "\n3=ADD", "\n4=DELETE ALL," "\n5=HELP" };

void setup() {

  Serial.begin(115200);         // this is for general debug
  while (!Serial) {
    ; // wait for serial port to connect. Needed for native USB port only
  }
  Serial.println();
  Serial.print("Bluetooth Programming Arduino init...");
  myBlueSerial.begin(19200); // this is control for Bluetooth module (KCX_BT_EMITTER)
  Serial.println(" completed!");

}  // end setup()

void loop() {
  static uint8_t menuPrinted = 0;

  if (0 == menuPrinted) {
    menuPrinted = 1;
    Serial.println("");
    Serial.println("   1 - Scan for Bluetooth receiver devices (such as speaker, headphones, etc.)");
    Serial.println("   2 - Display stored auto-connect Bluetooth receiver devices");
    Serial.println("   3 - Add one auto-connect Bluetooth receiver device to storage");
    Serial.println("   4 - Delete all auto-connect Bluetooth receiver devices from storage");
    Serial.println("   5 - HELP");
    Serial.print("==> ");
  }

  if (Serial.available()) {
    uint8_t myChoice = 0;

    menuPrinted = 0;
    myChoice = getSerial_uint8_t();
    if ((0 == myChoice) || (myChoice > 5)) {
      Serial.println("ERROR - choice must be 1 through 5");
    } else {
      Serial.println(menuOptions[myChoice-1]);
      processCommand(myChoice);
    }
  }

  // testEcho(); // this one is useful for debugging command sequences
} // end loop()


/////////////////////////////////////////////////////////////////////////////////////////////////////////
// processCommand(uint8_t theChoice)
//    performs one of the four menu options
//    as needed, reports scan info from Bluetooth
//
void processCommand(uint8_t theChoice) {
  uint8_t addlinkOk = 0;

  reportBlueCom();
  switch (theChoice) {
    case 1: // 1 - Scan for Bluetooth receiver devices (such as speaker, headphones, etc.)");
      sendBlueCmds(cmdsScan, (uint8_t) NUMOF(cmdsScan));
      // need to hang around a little more
      loopReportBlueCom();
      break;
    case 2: // 2 - Display stored auto-connect Bluetooth receiver devices");
      sendBlueCmds(cmdsDispRAM, (uint8_t) NUMOF(cmdsDispRAM));
      break;
    case 3: // 3 - Add one auto-connect Bluetooth receiver device to storage");
      addlinkOk = buildADDLINKADD(cmd_bld_ADDLINKADD, NUMOF(cmd_bld_ADDLINKADD) - strlen(cmd_ADDLINKADD)-2);
      if (0 != addlinkOk) {
        reportBlueCom();
        addlinkOk = buildADDLINKNAME(cmd_bld_ADDLINKNAME, NUMOF(cmd_bld_ADDLINKNAME) - strlen(cmd_ADDLINKNAME)-2);
      }
      if (0 != addlinkOk) {
        reportBlueCom();
        sendBlueCmds(cmdsAddRAM, (uint8_t) NUMOF(cmdsAddRAM));
        // need to hang around a little more
        loopReportBlueCom();
      } else {
        reportBlueCom();
        Serial.println("");
        Serial.println("User aborted storing MAC address for the Bluetooth speaker or headphones\n");
      }
      break;
    case 4: // 4 - Delete all auto-connect Bluetooth receiver devices from storage");
      sendBlueCmds(cmdsClearRAM, (uint8_t) NUMOF(cmdsClearRAM));
      loopReportBlueCom();
      break;
    case 5: // 5 - HELP");
      sendBlueCmds(cmdsHelp);
      loopReportBlueCom();
      break;
  } // end switch()
  Serial.println("\n--- KCX_BT_EMITTER PROGRAMMING STEP COMPLETE ---");
} // end processCommand()

/////////////////////////////////////////////////////////////////////////////////////////////////////////
// buildADDLINKADD(char * cmdAddr, uint16_t cmdMaxLen)
//    builds a RAM AT+ADDLINKADD command from user input
//
// NOTE: the hex MAC Address sent in the AT command must be exactly 12 characters
//
uint8_t buildADDLINKADD(char * cmdAddr, uint16_t cmdMaxLen) {
  char myLowerCase[15]; // never want to over-run
  uint8_t myNumChars = 0;
  uint8_t myStart = 0;
  char const * zeroFill = "000000000000";
  Serial.println("");
  Serial.println("Enter the unique MAC address for the Bluetooth speaker or headphones; it starts with 0x");
  Serial.println("    upper or lower case does not matter; maximum of 12 characters after the 0x");
  Serial.println("To abort adding an auto-connect Bluetooth receiver device to storage, just enter an empty line");
  Serial.print("==> ");
  while (!Serial.available()) {
    ; // wait
  }
  Serial.println(" ");
  // reportBlueCom();
  myNumChars = getSerial_chars();
  if (0 == myNumChars) {
    return(0); // abort
  }
  if (('0' == inBytes[0]) && ('x' == tolower(inBytes[1]))) {
    myStart = 2;
  }
  myNumChars -= myStart;
  if (DEBUG_SERIAL_IN) {
    Serial.print("   input string |");
    Serial.print(inBytes);
    Serial.print("| myStart ");
    Serial.print(myStart);
    Serial.print(" myNumChars ");
    Serial.println(myNumChars);
  } // end if (DEBUG_SERIAL_IN)
  if (myNumChars > 12) {
    Serial.println("Abort - more than 12 characters");
    return(0); // abort
  }
  for (int j = myStart; (j < (myNumChars+myStart)) && (0 != inBytes[j]); j++) {
    if (0 == isxdigit(inBytes[j])) {
      Serial.print("Abort - non-hex digit: ");
      Serial.print(inBytes[j]);
      Serial.print(" j ");
      Serial.println(j);
      return(0); // abort
    }
    myLowerCase[j] = tolower(inBytes[j]);
  }
  myLowerCase[myNumChars+myStart] = 0;
  Serial.print("\nYour entry \"");
  Serial.print(inBytes);
  Serial.println("\" was accepted");
  strcpy(cmdAddr, cmd_ADDLINKADD);
  strcat(cmdAddr, &zeroFill[myNumChars]);
  strcat(cmdAddr, &myLowerCase[myStart]);
  return(1); // successful command build
} // end buildADDLINKADD()

/////////////////////////////////////////////////////////////////////////////////////////////////////////
// buildADDLINKNAME(char * cmdAddr, uint16_t cmdMaxLen)
//    builds a RAM AT+ADDLINKNAME command from user input
//
uint8_t buildADDLINKNAME(char * cmdAddr, uint16_t cmdMaxLen) {
  uint8_t myNumChars = 0;
  char const * zeroFill = "000000000000";
  Serial.println("");
  Serial.println("Enter the name you choose for this device; it is OK to place spaces between words");
  Serial.println("    maximum of 20 characters total");
  Serial.println("To abort adding an auto-connect Bluetooth receiver device to storage, just enter an empty line");
  Serial.print("==> ");
  while (!Serial.available()) {
    ; // wait
  }
  Serial.println(" ");
  // reportBlueCom();
  myNumChars = getSerial_chars();
  if (0 == myNumChars) {
    return(0); // abort
  }
  if (myNumChars > 20) {
    Serial.println("Abort - more than 20 characters");
    return(0); // abort
  }
  Serial.print("\nYour entry \"");
  Serial.print(inBytes);
  Serial.println("\" was accepted");
  strcpy(cmdAddr, cmd_ADDLINKNAME);
  strcat(cmdAddr, inBytes);
  return(1); // successful command build
} // end buildADDLINKNAME()


/////////////////////////////////////////////////////////////////////////////////////////////////////////
// getSerial_chars()
//    gets character string from USB serial; removes EOL chars; stores in inBytes[] zero terminated
//
//    returns number of characters in inBytes
//
// no code to flag input over-run
// stores zero-terminated string in inBytes
//
uint8_t getSerial_chars() {
  static unsigned char myChar;
  static uint8_t idx = 0;

  idx = 0;
  while (Serial.available()) {
    myChar = Serial.read();
    if (DEBUG_SERIAL_IN) {
      Serial.print("\n  getSerial_chars got myChar 0x");
      Serial.print(myChar, HEX);
    } // end if(DEBUG_SERIAL_IN)
    if (((int) myChar) >= 0x20) { // if it is space or higher
      if (DEBUG_SERIAL_IN) { Serial.print(" >= 0x20 "); }
      if ((idx+2) <= NUMOF(inBytes)) {
        inBytes[idx++] = myChar;
        if (DEBUG_SERIAL_IN) {
          Serial.print("count of inBytes #");
          Serial.println(idx);
        } // end if(DEBUG_SERIAL_IN)
      } else {
        if (DEBUG_SERIAL_IN) {
          Serial.print(" not stored; idx ");
          Serial.print(idx);
          Serial.print(" not stored; NUMOF(inBytes) ");
          Serial.println(NUMOF(inBytes));
        } // end if(DEBUG_SERIAL_IN)
      }
      delay(5);
    } else {
      delay(5);
        if (DEBUG_SERIAL_IN) {
          Serial.print(" --- not stored! Count of inBytes #");
          Serial.println(idx);
        } // end if(DEBUG_SERIAL_IN)
      while (Serial.available()) {
        myChar = Serial.read();
        delay(5);
      }
      break;
    }
  } // end try to read input to the end of line

  inBytes[idx] = 0;
  if (DEBUG_SERIAL_IN) {
    Serial.print("\n  getSerial_chars idx ");
    Serial.print(idx);
    Serial.print(" inBytes[idx] 0x");
    Serial.print(inBytes[idx], HEX);
    Serial.print(" inBytes |");
    Serial.print(inBytes);
    Serial.println("|");
  } // end if(DEBUG_SERIAL_IN)
  return(idx);
} // end getSerial_chars()

/////////////////////////////////////////////////////////////////////////////////////////////////////////
// getSerial_uint8_t()
//    gets single-digit decimal number from USB serial; returns the number itself (not ASCII)
//
uint8_t getSerial_uint8_t() {
  getSerial_chars();
  if (DEBUG_SERIAL_IN) {
    Serial.print("\n  getSerial_uint8_t inBytes[0] 0x");
    Serial.print(inBytes[0], HEX);
    Serial.print(" converted to ");
    Serial.println(uint8_t (inBytes[0]-0x30), HEX);
  } // end if(DEBUG_SERIAL_IN)
  return(uint8_t (inBytes[0]-0x30)); // subtract ASCII 0
} // end getSerial_uint8_t()


/////////////////////////////////////////////////////////////////////////////////////////////////////////
// testEcho()
//    Surprisingly tricky routine to echo chars back and forth between the USB serial port
//       and the KCX_BT_EMITTER serial port.
//    Not super hard but there are some things to watch out for like different baud rates
//
void testEcho() {

  static char eolBytes[10];
  static unsigned char mychar;
  static unsigned int idx = 0;
  static unsigned int odx = 0;
  static unsigned int edx = 0;
  int loopIdx;

  while (Serial.available()) {
    mychar = Serial.read(); // this side is faster
    if (((int) mychar) >= 0x20) { // if it is space or higher
      inBytes[idx++] = mychar;
      delay(5);
    } else {
      eolBytes[edx++] = mychar;
      delay(5);
      while (Serial.available()) {
        mychar = Serial.read(); // this side is faster
        eolBytes[edx++] = mychar;
        delay(5);
      }
      break;
    }
  } // end try to read input to the end of line

  if (idx > 0) { // if anything to send to Bluetooth chip
    // display the input
    for (odx = 0; odx < idx; odx++) {
      Serial.print("char 0x");
      Serial.print((int) inBytes[odx], HEX);
      Serial.print(" ");
      Serial.println(inBytes[odx]);
      // printf("\neol char 0x%02X %c\n", (int) inBytes[odx], inBytes[odx]);
    }
    for (odx = 0; odx < edx; odx++) {
      Serial.print("\neol char 0x");
      Serial.println((int) eolBytes[odx], HEX);
      // printf("\neol char 0x%02X\n", (int) eolBytes[odx]);
    }
    // send input (without EOL) to Bluetooth module
    inBytes[idx] = 0;
    sendBlueCmd(inBytes);
    // Clean up
    idx = edx = 0;
  } else { // just display what there is if anything
    if (myBlueSerial.available()) {
      reportBlueCom();
    }
  }
  
} // end testEcho()

/////////////////////////////////////////////////////////////////////////////////////////////////////////
// sendBlueCmds(const char * cmdArray[], const uint8_t numCmds)
//    Sends a number of AT commands to KCX_BT_EMITTER module
//    Will report back any response or scan output from the module
//
void sendBlueCmds(const char * cmdArray[], const uint8_t numCmds) {

  for (int cmdIdx = 0; cmdIdx < numCmds; cmdIdx += 1) {
    Serial.println("");
    Serial.print("--CMD ");
    Serial.print(cmdIdx);
    Serial.print(" ");
    Serial.println(cmdArray[cmdIdx]);
    sendBlueCmd((char *) cmdArray[cmdIdx]);
  }

  delay(100);

} // end sendBlueCmds()

/////////////////////////////////////////////////////////////////////////////////////////////////////////
// sendBlueCmd( char * cmd )
//    Sends one AT-style zero-terminated string to the Bluetooth module
//
void sendBlueCmd( char * cmd ) {
  // Serial.println(cmd); // send this before sending to device
  myBlueSerial.print(cmd);
  loopReportBlueCom();
} // end sendBlueCmd()

/////////////////////////////////////////////////////////////////////////////////////////////////////////
// reportBlueCom()
//    Reports back any response or scan output from the Bluetooth module
//    Returns number of characters seen
//
unsigned int reportBlueCom() {
  unsigned int idx = 0;
  unsigned int odx = 0;

  while (myBlueSerial.available()) {
    inBytes[idx++] = myBlueSerial.read();
  }
  if (idx > 0) {
    odx = 0;
    for (odx = 0; odx < idx; odx += 1) {
      Serial.print(inBytes[odx]);
    }
  } // if anything received from Bluetooth chip
  return(idx);
} // end reportBlueCom()

/////////////////////////////////////////////////////////////////////////////////////////////////////////
// loopReportBlueCom()
//    Loops reporting back any response or scan output from the Bluetooth module
//    Returns number of characters seen on the last loop
//
unsigned int loopReportBlueCom() {
  int loopIdx;
  unsigned int numBytes;
  for (loopIdx = 0; loopIdx < NUMWAIT; loopIdx += 1) {
    numBytes = reportBlueCom();
    delay(5);
  }
  return(numBytes);
} // end loopReportBlueCom()

**Comment by Mark-MDO47** [comment]
The things that you reported as errors are warnings. It is my judgement that they are OK. Feel free to correct them in your copy.
As for the help command, could you show a listing of what happens when you invoke it?
Also be aware that these devices have many different versions of what chip is used and what firmware is in the chip. It is possible that the chip you are communicating with does not respond to that command.
I look forward to hearing from you.

**Comment by Mark-MDO47** [comment]
I took a look at the documentation that I have for this module and do not see an AT+HELP command that you are trying. If you look from lines 74 to 145 here, those commands are the only commands that I am aware of
- https://github.com/Mark-MDO47/BluetoothAudioTransmitter_KCX_BT_EMITTER/blob/master/ProgrammingArduino/ProgrammingArduino.ino

The main readme for this repository, near the end where it says "Best information on the Bluetooth module I could find is here", shows where I got this list of commands.
- https://github.com/Mark-MDO47/BluetoothAudioTransmitter_KCX_BT_EMITTER#readme
